name: Build Tkinter App

on:
  release:
    types: [created] # se ejecuta cuando creas un release en GitHub

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear ejecutable con PyInstaller
        run: |
          pyinstaller --onefile --windowed app.py

      - name: Subir ejecutable al Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
